### ISSUE TITLE
nuevas branchs 

### ISSUE THREAD

**Issue by GuillermoMajano** [gophers-latam/GoKey#25]
Se pueden crear nuevas branchs para las features que están en desarrollo y darle nombres, ejemplo: go-key-0.x? (para referirnos a la versión que se está trabajando). la main seria la ultima versión "estable". 

Saludos.

**Comment by zeroidentidad** [comment]
Hay una rama de @tomiok pendiente de merge que no esta claro los cambios manejados y por que quedo abandonada. También han habido ramas que se eliminaron después de su finalización y que en local causan bloqueo para seguimiento u obtención de cambios remotos, seria de ahora en adelante preservar las ramas de tareas finalizadas remotamente y solo eliminar localmente.

**Comment by tomiok** [comment]
hola chicos, dentro de poco vamos a ir retomando estos proyectos, pero por ahora no veo pull requests abiertos, Master es la ultima

**Comment by zeroidentidad** [comment]
que paso con los cambios en https://github.com/gophers-latam/GoKey/tree/fix-cache-tests

**Comment by tomiok** [comment]
https://github.com/gophers-latam/GoKey/issues/25#issuecomment-1474521962
los elimine y puse en la rama nueva!

De todas formas, podes crear las ramas que quieras pero no de release todavia, vamos a esperar a tener algunas funcionalidades mas (si subimos releases o versiones, algunos bots la van a tomar y publicar en blogs y Twitter)
