### ISSUE TITLE
Agregar limite maximo al cache, validar el limite en cada entrada

### ISSUE THREAD

**Issue by tomiok** [gophers-latam/GoKey#30]

**Comment by zeroidentidad** [comment]
Rama con los cambios relacionados: [set-maxlimit_check-limitinput](https://github.com/gophers-latam/GoKey/tree/set-maxlimit_check-limitinput)

Cambios para code review antes de hace PR

**Comment by tomiok** [comment]
@zeroidentidad hace el PR de tu rama a main

**Comment by zeroidentidad** [comment]
> @zeroidentidad hace el PR de tu rama a main

va que va
